CREATE TABLE nurses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- change to uuid for randomization
    name TEXT NOT NULL,
    nick_name TEXT NOT NULL,
    phone VARCHAR(10) NOT NULL,
    voalte VARCHAR(10) NOT NULL,
    email TEXT NOT NULL,
    standby DATE,
    tripled DATE,
    float DATE
);

CREATE TABLE techs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- change to uuid for randomization
    name TEXT NOT NULL,
    nick_name TEXT NOT NULL,
    phone VARCHAR(10) NOT NULL,
    voalte VARCHAR(10) NOT NULL,
    email TEXT NOT NULL,
    standby DATE,
    float DATE
);