CREATE TABLE patients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- change to uuid for randomization
    name TEXT NOT NULL, -- figure out how to have less identifiables
    level_of_care TEXT NOT NULL DEFAULT 'icu',
    resp TEXT NOT NULL DEFAULT 'vent',
    code TEXT NOT NULL DEFAULT 'full',
    age INTEGER NOT NULL,
    diagnosis TEXT NOT NULL,
    comments TEXT NOT NULL,
    down_grade BOOLEAN NOT NULL DEFAULT 'false',
    roomNum INTEGER REFERENCES rooms(number) ON DELETE SET NULL,
    nurseId INTEGER REFERENCES nurses(id) ON DELETE SET NULL,
    techId INTEGER REFERENCES techs(id) ON DELETE SET NULL
);

ALTER TABLE rooms
  ADD COLUMN
    ptId INTEGER REFERENCES patients(id)
    ON DELETE SET NULL;
